# Generated by Django 4.2.3 on 2023-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=200)),
                ('kcal', models.FloatField()),
                ('water', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('asche', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('sugar', models.FloatField()),
                ('dietaryFibre', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('sodium', models.FloatField()),
                ('vitaminA', models.FloatField()),
                ('vitaminC', models.FloatField()),
                ('vitaminD', models.FloatField()),
                ('vitaminB1', models.FloatField()),
                ('vitaminB2', models.FloatField()),
                ('vitaminB3', models.FloatField()),
                ('retinol', models.FloatField()),
                ('betaCarotene', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('saturatedFattyAcid', models.FloatField()),
                ('transFattyAcid', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kcal', models.FloatField()),
                ('water', models.FloatField()),
                ('protein', models.FloatField()),
                ('fat', models.FloatField()),
                ('asche', models.FloatField()),
                ('carbohydrate', models.FloatField()),
                ('sugar', models.FloatField()),
                ('dietaryFibre', models.FloatField()),
                ('calcium', models.FloatField()),
                ('iron', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('sodium', models.FloatField()),
                ('vitaminA', models.FloatField()),
                ('vitaminC', models.FloatField()),
                ('vitaminD', models.FloatField()),
                ('vitaminB1', models.FloatField()),
                ('vitaminB2', models.FloatField()),
                ('vitaminB3', models.FloatField()),
                ('retinol', models.FloatField()),
                ('betaCarotene', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('saturatedFattyAcid', models.FloatField()),
                ('transFattyAcid', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('result', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
