# Generated by Django 4.0.3 on 2023-07-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('bmi', models.FloatField()),
                ('arginine', models.FloatField()),
                ('tyrosine', models.FloatField()),
                ('CoenzymeQ10', models.FloatField()),
                ('betaine', models.FloatField()),
                ('BloodPressure', models.FloatField()),
                ('BloodSugar', models.FloatField()),
                ('magnesium', models.FloatField()),
                ('calcium', models.FloatField()),
                ('BoneMass', models.FloatField()),
                ('iron', models.FloatField()),
                ('zinc', models.FloatField()),
                ('vitaminC', models.FloatField()),
                ('vitaminD', models.FloatField()),
                ('cholesterol', models.FloatField()),
                ('NeutralFat', models.FloatField()),
                ('obesity', models.FloatField()),
                ('BodyFat', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
