# Generated by Django 4.0.3 on 2023-07-14 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisnap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('result', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
